/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RidesIndexRouteImport } from './routes/rides/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RidesRideIdRouteImport } from './routes/rides/$rideId'
import { Route as DriverIncidentsRouteImport } from './routes/driver/incidents'
import { Route as DriverDashboardRouteImport } from './routes/driver/dashboard'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminRoutesRouteImport } from './routes/admin/routes'
import { Route as AdminLiveMapRouteImport } from './routes/admin/live-map'
import { Route as AdminFleetRouteImport } from './routes/admin/fleet'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as DriverTripTripIdRouteImport } from './routes/driver/trip.$tripId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesIndexRoute = RidesIndexRouteImport.update({
  id: '/rides/',
  path: '/rides/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesRideIdRoute = RidesRideIdRouteImport.update({
  id: '/rides/$rideId',
  path: '/rides/$rideId',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIncidentsRoute = DriverIncidentsRouteImport.update({
  id: '/driver/incidents',
  path: '/driver/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDashboardRoute = DriverDashboardRouteImport.update({
  id: '/driver/dashboard',
  path: '/driver/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoutesRoute = AdminRoutesRouteImport.update({
  id: '/admin/routes',
  path: '/admin/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveMapRoute = AdminLiveMapRouteImport.update({
  id: '/admin/live-map',
  path: '/admin/live-map',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFleetRoute = AdminFleetRouteImport.update({
  id: '/admin/fleet',
  path: '/admin/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverTripTripIdRoute = DriverTripTripIdRouteImport.update({
  id: '/driver/trip/$tripId',
  path: '/driver/trip/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/live-map': typeof AdminLiveMapRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/incidents': typeof DriverIncidentsRoute
  '/rides/$rideId': typeof RidesRideIdRoute
  '/admin': typeof AdminIndexRoute
  '/rides': typeof RidesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/driver/trip/$tripId': typeof DriverTripTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/live-map': typeof AdminLiveMapRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/incidents': typeof DriverIncidentsRoute
  '/rides/$rideId': typeof RidesRideIdRoute
  '/admin': typeof AdminIndexRoute
  '/rides': typeof RidesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/driver/trip/$tripId': typeof DriverTripTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/live-map': typeof AdminLiveMapRoute
  '/admin/routes': typeof AdminRoutesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/incidents': typeof DriverIncidentsRoute
  '/rides/$rideId': typeof RidesRideIdRoute
  '/admin/': typeof AdminIndexRoute
  '/rides/': typeof RidesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/driver/trip/$tripId': typeof DriverTripTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/admin/bookings'
    | '/admin/fleet'
    | '/admin/live-map'
    | '/admin/routes'
    | '/auth/login'
    | '/auth/register'
    | '/driver/dashboard'
    | '/driver/incidents'
    | '/rides/$rideId'
    | '/admin'
    | '/rides'
    | '/api/auth/$'
    | '/driver/trip/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/admin/bookings'
    | '/admin/fleet'
    | '/admin/live-map'
    | '/admin/routes'
    | '/auth/login'
    | '/auth/register'
    | '/driver/dashboard'
    | '/driver/incidents'
    | '/rides/$rideId'
    | '/admin'
    | '/rides'
    | '/api/auth/$'
    | '/driver/trip/$tripId'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/admin/bookings'
    | '/admin/fleet'
    | '/admin/live-map'
    | '/admin/routes'
    | '/auth/login'
    | '/auth/register'
    | '/driver/dashboard'
    | '/driver/incidents'
    | '/rides/$rideId'
    | '/admin/'
    | '/rides/'
    | '/api/auth/$'
    | '/driver/trip/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  DashboardRoute: typeof DashboardRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminFleetRoute: typeof AdminFleetRoute
  AdminLiveMapRoute: typeof AdminLiveMapRoute
  AdminRoutesRoute: typeof AdminRoutesRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  DriverDashboardRoute: typeof DriverDashboardRoute
  DriverIncidentsRoute: typeof DriverIncidentsRoute
  RidesRideIdRoute: typeof RidesRideIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  RidesIndexRoute: typeof RidesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DriverTripTripIdRoute: typeof DriverTripTripIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/': {
      id: '/rides/'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof RidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/$rideId': {
      id: '/rides/$rideId'
      path: '/rides/$rideId'
      fullPath: '/rides/$rideId'
      preLoaderRoute: typeof RidesRideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/incidents': {
      id: '/driver/incidents'
      path: '/driver/incidents'
      fullPath: '/driver/incidents'
      preLoaderRoute: typeof DriverIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/dashboard': {
      id: '/driver/dashboard'
      path: '/driver/dashboard'
      fullPath: '/driver/dashboard'
      preLoaderRoute: typeof DriverDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/routes': {
      id: '/admin/routes'
      path: '/admin/routes'
      fullPath: '/admin/routes'
      preLoaderRoute: typeof AdminRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/live-map': {
      id: '/admin/live-map'
      path: '/admin/live-map'
      fullPath: '/admin/live-map'
      preLoaderRoute: typeof AdminLiveMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fleet': {
      id: '/admin/fleet'
      path: '/admin/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AdminFleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/trip/$tripId': {
      id: '/driver/trip/$tripId'
      path: '/driver/trip/$tripId'
      fullPath: '/driver/trip/$tripId'
      preLoaderRoute: typeof DriverTripTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  DashboardRoute: DashboardRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminFleetRoute: AdminFleetRoute,
  AdminLiveMapRoute: AdminLiveMapRoute,
  AdminRoutesRoute: AdminRoutesRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  DriverDashboardRoute: DriverDashboardRoute,
  DriverIncidentsRoute: DriverIncidentsRoute,
  RidesRideIdRoute: RidesRideIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  RidesIndexRoute: RidesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DriverTripTripIdRoute: DriverTripTripIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
